### ISSUE TITLE
Cleanup Javadoc for ContainerProvider

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/websocket-api#252]
The line lengths are somewhat varied and the description for getCotnainer() doesn't look write. It doesn;t load the implementation, it creates an instance.

**Comment by joakime** [comment]
Do we want to provided advice in `#getWebSocketContainer()` about repeated use of that method - see #212 

Even if #212 is fixed, the older code using the original behavior would still be at risk if using `#getWebSocketContainer()` without being aware of the repercussions.

**Comment by markt-asf** [comment]
I don't agree with the premise of #212 and I have concerns regarding the proposed addition. I'm not against adding to the `#getWebSocketContainer()` Javadoc if necessary but I don't think there is consensus on what, if anything, should be added. My preference is to handle any Javadoc changes as a result of #212 as part of the fix for #212 and not try and consider them here.

**Comment by joakime** [comment]
Fair point.
I'll work up something for the mailing list about "Obtain a new instance of a WebSocketContainer." and how #212 and #230 overlap with this javadoc and the prior cache proposal.

**Comment by markt-asf** [comment]
Sounds good.
