### ISSUE TITLE
Unable to bind client to IP or use Socks Proxy

### ISSUE THREAD

**Issue by Pocketpac** [eclipse-ee4j/websocket-api#258]
I am unable to bind a client to an IP to use for outgoing connections, and whenever I try to use a socks proxy it says the Tyrus client does not support socks based proxies.

I run a rather large chat bot connecting via websockets, one per channel, and their rate limiting is based on IP. I know what I am tying to do is not ideal, but it is the only potential option available to me, so any assistance would be much appreciated.

**Comment by markt-asf** [comment]
This is an issue for Tyrus (the particular implementation you are using) rather than the WebSocket API and specification.

**Comment by joakime** [comment]
If this is Tyrus specific, then you can find that project at https://github.com/eclipse-ee4j/tyrus
