### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/websocket-api#259]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by joakime** [comment]
What qualifies "first version" here? (just the artifacts? and/or the spec document too?)
There's no spec doc, looks like we are on the hook to create it from scratch, clean room style (which means both @markt-asf and myself are not legally allowed to write it as we've both seen the original documents)
There's no settled opinion yet on OSGi manifests (currently broken in javax.websocket and incompatible with the rest of the eclipse ecosystem)
There's no settled opinion yet on JPMS manifests (currently missing in javax.websocket)

**Comment by m0mus** [comment]
Just APIs. We are not talking about the spec document at all. The task is to build a release pipeline, so we can release the project to OSSRH staging repository and other projects can consume it. 
Both OSGi and JPMS issues should be fixed before the **public** release. Do you have issues created for it?

**Comment by m0mus** [comment]
@joakime @markt-asf This task is still unassigned. As project leads, please assign it to someone from your team.

**Comment by joakime** [comment]
CI is already setup at - https://ci.eclipse.org/websocket/

**Comment by joakime** [comment]
Other possibly related issues to resolve.

* #260 - JPMS support in websocket api jars
* #261 - OSGi manifest updates for ServiceLoader requirements of websocket api jars

**Comment by markt-asf** [comment]
Jenkins build has been created. Waiting for appropriate credentials to be configured so it can be tested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539202

**Comment by markt-asf** [comment]
GitHub credentials have been created but appear to be invalid. Raised https://bugs.eclipse.org/bugs/show_bug.cgi?id=540250

**Comment by m0mus** [comment]
From Maxim Nesen:

As I've noticed, the configuration of the release job is not complete. To be exact, it is not possible to configure SSH Agent in the Build configuration section. That is the reason why job fails later on - it has no credentials to perform a push into repository. 
I've filed a bug to Eclipse  https://bugs.eclipse.org/bugs/show_bug.cgi?id=540452

**Comment by Tomas-Kraus** [comment]
I added the same request into https://bugs.eclipse.org/bugs/show_bug.cgi?id=540250 :)

**Comment by senivam** [comment]
for now release job is fixed and all jobs are moved to the new infrastructure.
So, link to release is:

https://jenkins.eclipse.org/websocket/view/all/job/websocket-api-release-build/

**Comment by joakime** [comment]
Per [feedback from @senivam](https://github.com/eclipse-ee4j/websocket-api/pull/277#issuecomment-434314682) this issue can now be closed.
