### ISSUE TITLE
JPMS Module Names for websocket-api

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/websocket-api#260]
We should start making both websocket-api jars more consumable by JPMS users.

We can start with declaring the `Automatic-Module-Name` and have an initial release.

But we should really declare a proper `module-info.(java|class)` to do this correctly.

**Comment by joakime** [comment]
We should pay attention to the outcome of eclipse-ee4j/ee4j#34 for answers on this.

**Comment by markt-asf** [comment]
That looks like `jakarta.websocket` and `jakarta.websocket-client` are the names we should be using.

**Comment by markt-asf** [comment]
Looking again, they need `.api` on the end (and the `-` changed to a `.`. I'll put together a PR for this.
