### ISSUE TITLE
Need updated spec-version-maven-plugin

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/websocket-api#266]
The current version has a hard-coded requirement that the groupId starts with `javax`. That breaks the build as we are using a groupId of `jakarta`

**Comment by joakime** [comment]
The `org/glassfish/spec/Spec.java` source has the following hardcoded expectation on `groupId`.

``` java
        if (jarType.equals(JarType.api)) {
            // verify that groupId starts with javax.
            if (!artifact.getGroupId().startsWith("javax.")) {
                errors.add(String.format(
                        "WARNING: groupId (%s) must start with \"javax\"",
                        artifact.getGroupId()));
            }
```

**Comment by joakime** [comment]
@m0mus please be aware of above issue using `jakarta` maven groupId

**Comment by m0mus** [comment]
https://github.com/javaee/spec-version-maven-plugin/issues/3

**Comment by m0mus** [comment]
Please temporary disable this plugin (or goal).

**Comment by markt-asf** [comment]
Done. Leaving this open to track the fact that we will need to update to the new plugin version when available and re-enable that goal.

**Comment by m0mus** [comment]
The new version (1.5) of the spec-version plugin is released. Jakarta groupId support is added there. See here for reference: https://github.com/javaee/spec-version-maven-plugin/pull/5
