### ISSUE TITLE
Change Maven coordinates

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/websocket-api#269]
All current API libraries shipped must be distributed to Maven Central under a sub-package of the `jakarta` groupId. Before the first release Maven coordinates of this project must be changed as it's described [here](https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates).

**Comment by joakime** [comment]
@m0mus this would require a fix/change? in the `org.glassfish.build:spec-version-maven-plugin` it would seem.
It fails the build if we try to use `jakarta` for just the maven `groupId` coordinate.

It seems to want both the maven `groupId` and the actual packages used to be the same. ugh.
Has this plugin been moved over with the rest of the ee4j efforts?

**Comment by joakime** [comment]
Reference Issue #266 for spec-version-maven-plugin problem

**Comment by markt-asf** [comment]
Fixed as part of #265

**Comment by ggam** [comment]
@markt-asf according to https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates the coordinates should be:
```<groupId>jakarta.websocket</groupId>
<artifactId>jakarta.websocket-all</artifactId>
<artifactId>jakarta.websocket-api</artifactId>
<artifactId>jakarta.websocket-client-api</artifactId>```

**Comment by joakime** [comment]
I'll submit new PR for this

**Comment by joakime** [comment]
@ggam PR #272 opened with corrected artifactIds

**Comment by ebourg** [comment]
Changing the Maven coordinates but not the Java package will lead to duplicate websocket api jars in projects and classpath conflicts. The groupId/artifactId is purely technical and shouldn't be affected by branding policies. Could you consider reverting to the javax coordinates?

**Comment by markt-asf** [comment]
Sorry, no. We have no control over that. It is mandated by Eclipse. I suggest you raise your concerns with the EE4J PMC.

**Comment by ebourg** [comment]
Thank you for the feedback Mark. Alone I doubt I'll have any weight to convince the PMC though.

**Comment by arjantijms** [comment]
@ebourg You'd likely also have to convince Oracle to give "us" (the Eclipse org basically) the full ownership, keys and what have you, to publish to the javax.* namespaces.

If you'd *really* want this, I suggest you start there. Even if you could convince the PMC, their hands would be tied too. We can't publish to something we don't own.

**Comment by ebourg** [comment]
@arjantijms Oracle doesn't own the Maven javax.* groupIds, it's up to Sonatype who manages the Maven Central repository to grant Eclipse the right to upload artifacts under these groupIds. Considering that Oracle donated the code to Eclipse I doubt Sonatype would refuse this right. Also, Sonatype is probably concerned about the integrity of the Maven ecosystem and perfectly understand the conflict potential behind highly popular APIs available under different coordinates.

**Comment by arjantijms** [comment]
@ebourg Sure, I don't know how the ownership legals exactly work, although I do think Oracle probably has other things in the javax.* namespace that aren't donated, so they can't transfer it fully.

Yet, if you think that Oracle doesn't own the javax.* groupIds, by all means try to convince Oracle, the PMC and Sonatype about that.

**Comment by ebourg** [comment]
The permissions on the Maven Central repository are hierarchical. Eclipse doesn't have to claim the whole javax.* upload rights, it can be limited to javax.<specname>.* while Oracle retains the javax.* rights.

**Comment by arjantijms** [comment]
@ebourg As this is an issue that holds for the entire Jakarta EE project, please take it up with Eclipse and Oracle directly. It's not something we can just decide here at the WebSocket level.

If you can strike a deal between Oracle and Eclipse so that we can both practically and legally use javax.<specname>.* in all projects that would be great.
