### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/websocket-api#275]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by markt-asf** [comment]
The EE4J_8 branch looks to be a long way from ready but it isn't as bad as it looks. Once we apply #267 (an approval is required) master will be in a releasable state and we'll just need to merge all the changes from master to EE4J_8.

**Comment by markt-asf** [comment]
As always, it wasn't quite that simple but we are there now.
https://oss.sonatype.org/content/groups/staging/jakarta/websocket/
