### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/websocket-api#287]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by markt-asf** [comment]
Done. Maven Central should sync shortly.

**Comment by joakime** [comment]
Can confirm.
It is present on maven central now ...

http://central.maven.org/maven2/jakarta/websocket/
