### ISSUE TITLE
Update Scope Statement for Jakarta API for WebSocket Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/websocket-api#291]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by joakime** [comment]
The proposed scope ...

> Jakarta WebSocket provides a specification document, API, and TCK that describes the integration of WebSockets into Java(R) applications.

Can be a bit confusing, as Java core (non EE) has a WebSocket client, and so does the eclipse-ee4j/websocket-api (different APIs).
However, eclipse-ee4j/websocket-api also has a Server, which the Java core (non EE) does not have.

Not sure how to limit the scope of the statement to just EE based projects.

**Comment by joakime** [comment]
How about ...

> The Jakarta WebSocket Project provides a specification document, API, and TCK for Jakarta based applications wanting a WebSocket Client or Server.

This also doesn't limit the scope to "Java(R)", nor does it mention "Java(R)".
As this effort can work equally well for other runtimes, such as Kotlin and Scala.

**Comment by waynebeaton** [comment]
The project will provide the "...specification document and supporting technical artifacts...". We still need know what the specification actually defines.

How about something like:

>The Jakarta WebSocket defines how Jakarta based applications create and manage WebSocket Clients and Servers.

**Comment by markt-asf** [comment]
Shouldn't that be "The Jakarta WebSocket Project..."? Otherwise +1.

**Comment by waynebeaton** [comment]
Focus on the specification itself. The project scope will be to provide the specification document and associated technical artifacts.

**Comment by joakime** [comment]
Scope statement updated at https://projects.eclipse.org/projects/ee4j.websocket
