### ISSUE TITLE
Change project name to Jakarta WebSocket

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/websocket-api#292]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by joakime** [comment]
What does "GitHub" in the checklist represent?
A renaming of `eclipse-ee4j/websocket-api` to `jakartaee/websocket` ?

**Comment by ivargrimstad** [comment]
@joakime What I meant with that is the descriptive name of the GitHub Project. I am not sure if we can do this ourselves or if it will involve @eclipsewebmaster to do it though...

**Comment by joakime** [comment]
Correct, the "Description" on a GitHub project needs a project admin (or organization admin) to perform that specific edit.

**Comment by kwsutter** [comment]
Along the lines of Jakarta Transactions, should this one be called Jakarta WebSockets (plural)?  I've always referred to this technology as WebSockets, but maybe that's not accurate?

**Comment by joakime** [comment]
I've requested admin access to this github repo at https://bugs.eclipse.org/bugs/show_bug.cgi?id=548123
Once I have it, I'll setup/change/edit the various namings and urls that this issue and #294 have been assigned here.

**Comment by joakime** [comment]
I think "Jakarta WebSocket" is sufficient.
After all it's not "Jakarta Servlets", its just "Jakarta Servlet"

**Comment by joakime** [comment]
I have just been given admin permission for the next 48 hours.

Project name has been changed - "Jakarta WebSocket"
Project WebSite has been linked to - https://projects.eclipse.org/projects/ee4j.websocket

Working on a PR for README and CONTRIBUTING now
