### ISSUE TITLE
Jakarta EE 8 TCK job

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/websocket-api#293]
To test Jakarta EE 8 compatibility we need to create a Jenkins job on project's Cloud Jenkins instance formally testing the API against the relevant TCK and as needed, relevant CTS subset tests. 

For projects that do not already have automated testing, there is provided parameterized Jenkins job that can be invoked to perform these tests. User provides a link to an Eclipse GlassFish test build and sets the test sub-set parameters:

- For CTS -- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
- For Stand-alone TCKs -- https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

Additional instructions and guidance for using and directly running TCKs is available on [this wiki](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run). Also in the [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck) project repository.

**Comment by markt-asf** [comment]
This looks like it needs to be closed to me. There is no implementation in this project to run the TCK against.

**Comment by joakime** [comment]
I agree.

I'm a bit stuck on the phrase "formally testing the API against the relevant TCK".
What does that mean from the point of view of a API only project/repository?  (I should go look at the servlet-api project too)
Isn't TCK testing done against implementations of an API?

The code in this repository consists only of an API. which is ...

* 16 interfaces (no code)
* 7 annotations (no code)
* 4 exceptions 
* 1 abstract class (`ContainerProvider`)
* 3 classes (`CloseReason`, `SendResult`, and `DefaultServerEndpointConfig`)

And all of these are covered by the `Tyrus` project and their eventual TCK testing.
eclipse-ee4j/tyrus

I don't see a similar TCK issue opened on their issue tracker.
Perhaps, once that is created, this issue can be closed and reference the Tyrus specific TCK issue?

Looking at the TCK tests for websocket, it seems that this TCK job requirement can never be satisfied from the point of view of this repository.
For example, all of the CDI tests inside of the websocket tree would never work here, as this project/repository does not have a dependency on CDI.

**Comment by senivam** [comment]
Websocket-api:
-TCK jobs: [websocket](https://jenkins.eclipse.org/websocket)
-TCK results: [summary.txt](https://jenkins.eclipse.org/websocket/job/TCK_run/lastSuccessfulBuild/artifact/websockettck/bin/summary.txt)

API is not tested separately, it's being integrated into tyrus/glassfish and TCK are run against glassfish with integrated websocket-api

**Comment by joakime** [comment]
@senivam correct.

But why is the TCK execution requirement part of this project?

If we look at the results listed in https://jenkins.eclipse.org/websocket/job/TCK_run/lastSuccessfulBuild/artifact/websockettck/bin/summary.txt

You have a series of tests against Tyrus behaviors, Weld Behaviors, & Glassfish Behaviors.

If we took the same TCK and ran it against Tomcat or Jetty would we have tested the 2 artifacts produced by this project?
Nope, we would have tested how Tomcat or Jetty provides implementations of this project's API and spec.

The TCK results linked above don't even test the 2 artifacts this project produces.

* `jakarta.websocket:jakarta.websocket-client-api:1.1.1` - for standalone clients - not apparently used by Glassfish when executing TCK.
* `jakarta.websocket:jakarta.websocket-api:1.1.1` - what is used by Glassfish 

When, in the future, the WebSocket TCK is finally updated to actually test for the various ways the Jakarta WebSocket project is intended to be used, testing against Glassfish will be inadequate. (example: Jakarta WebSocket - Server API can be used outside of a Servlet container, and there are many existing implementations currently like that, but the TCK expects/mandates Servlet and CDI which is actually not part of the Jakarta WebSocket Spec).

**Comment by arjantijms** [comment]
@joakime this issue indeed did came up during the Jakarta EE Specification Committee weekly meeting, and for a moment it was suggested to only run the signature test against the API. However, some API artefacts do contain code (some even quite comprehensively, such as JSF), so running the standalone TCK against a compatible implementation using the produced API artefact is just a matter of ensuring that the API produced by this project is reasonably correct.

I'm sure the TCK can be expanded in the future for your additional concerns.

**Comment by joakime** [comment]
I guess the fundamental question is ...

Is the current TCK requirement for this project a short term mandate? 
If so, then full steam ahead!

In the long run though, the Jakarta WebSocket TCK will need to have 3 modes (standalone client, standalone server container, servlet server container) to satisfy the existing spec (let alone what happens to the spec once we update it for WebSocket over HTTP/2)

Will that be 3 TCK jobs?  
1. Standalone Client - Tyrus has an implementation of this.
2. Standalone Server Container - Glassfish is not appropriate for this.  We need an implementation without Servlet and CDI to test this.
3. Servlet Server Container - Glassfish and Tyrus have an implementation of this. 

Current WebSocket TCK jobs that don't fit into the above need to be moved to the appropriate projects (such as the existing CDI tests in the websocket TCK)
