### ISSUE TITLE
Restore Oracle <organization> in pom.xml

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/websocket-api#306]
In reviewing the maven-javadoc-configuration for Issue #295 and PR #304 and PR #305 it was discovered that the Copyright bottom header is bad and is missing the Oracle copyright notice.

The initial contribution of this project is at commit id 7dfd4b58e7bae70999fda4ced7a17a15f74aba2f

The initial pom.xml, as donated, in that commit, is ...
https://github.com/eclipse-ee4j/websocket-api/blob/7dfd4b58e7bae70999fda4ced7a17a15f74aba2f/api/pom.xml

Which has a declared `${project.organization}` section. (yay!)
https://github.com/eclipse-ee4j/websocket-api/blob/7dfd4b58e7bae70999fda4ced7a17a15f74aba2f/api/pom.xml#L60-L63

The parent pom `net.java:jvnet-parent:5` does not contain this section (and that parent has no parent of its own).
https://central.maven.org/maven2/net/java/jvnet-parent/5/jvnet-parent-5.pom

I can see that the `<organization>` was removed in the websocket pom, as the parent pom had one (per the comment).
3472dda01fcb064e708f6296b1d091e09dac1231

So that means the `1.1.1-RELEASE` of websocket had the wrong organization declared, and the wrong copyright on the javadoc.
We need to restore this `<organization>` section, and the resulting Copyright header on the javadoc as well.

Looking at the copyright bottom footer on json-api it seems that they have a odd year range.
See: https://github.com/eclipse-ee4j/jsonp/blob/EE4J_8/api/pom.xml

``` xml
Copyright &#169; 2012&#x2013;{currentYear} Oracle and/or its affiliates. All rights reserved.<br>
```

Where did the 2012 and 2013 years come from?
What should the start range for websocket be?

**Comment by m0mus** [comment]
@joakime According to [this](https://jcp.org/en/jsr/detail?id=356) the inception year for WebSocket API should be 2012. So the range is 2012-2019.  

What's odd in JSONP years range? The generated footer looks like this:
```
Copyright © 2012–2019 Oracle and/or its affiliates. All rights reserved.
```
Based on [this](https://jcp.org/en/jsr/detail?id=353) the first release was done in 2012.

Organization is defined in the parent pom. See [here](https://github.com/eclipse-ee4j/ee4j/blob/master/parent/pom.xml) as

```
<organization>
        <name>Eclipse Foundation</name>
        <url>https://www.eclipse.org</url>
    </organization>
```

Which is correct for all EE4J projects.

**Comment by joakime** [comment]
> According to [this](https://jcp.org/en/jsr/detail?id=356) the inception year for WebSocket API should be 2012. So the range is 2012-2019.

That means the `<bottom>` should be `2012-{currentYear}` for year range.  Thanks.

> What's odd in JSONP years range? The generated footer looks like this:

Ah, I see, my mental parsing of `2012&#x2013;{currentYear}` looked like `2012-2013;2019` as a result.
Not seeing the `2013` as the "EN DASH" ([Hex Code Point 2013](http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%E2%80%93&mode=char)).

> ``` xml
> <organization>
>     <name>Eclipse Foundation</name>   
>     <url>https://www.eclipse.org</url>
> </organization>
> ```
> Which is correct for all EE4J projects.

But incorrect for projects that use this parent pom and also ....

1. Don't have their own `<organization>` section (overriding the one from the parent pom)
2. Don't have a maven-javadoc-plugin `<bottom>` configuration defined. (a surprising number of projects are like this. eg: servlet-api)

Why is this combination incorrect?
Well, the default `<bottom>` configuration that the maven-javadoc-plugin will use is based on information from the computed "effective pom".
And it is computed like this (variables starting with `${project.` are from the projects computed effective-pom) ...

``` xml
<p class="legalCopy"><small>Copyright &#169; ${project.inceptionYear}-${currentYear} - <a href="${project.organization.url}">${project.organization.name}</a>. All Rights Reserved.</small></p>
```

Which will produce a Javadoc that says ...

``` xml
<p class="legalCopy"><small>Copyright &#169; 2017-2019 <a href="https://www.eclipse.org">Eclipse Foundation</a>. All Rights Reserved.</small></p>
```

That @bshannon says is incorrect, as the donated code is Oracle copyright, and should have the Oracle copyright present on the generated Javadoc.

Restoring the `<organization>` is going to be important seeing as how many existing maven plugins use that information.

> Maven Philosophy: Convention over Configuration

But now, what's the correct language for the `<bottom>` section?

[jms-api](https://github.com/eclipse-ee4j/jms-api/blob/master/api/pom.xml) has:
``` xml
Copyright 1997-2018 Oracle America Inc. Copyright 2019 Contributors to the Eclipse Foundation.  All rights reserved.
```

* No current year for Oracle. (kinda makes sense)
* No affiliates mentioned for Oracle section.
* 2nd copyright with `{currentYear}` hardcoded for Contributors to Eclipse
* No speclicense link

[json-api](https://github.com/eclipse-ee4j/jsonp/blob/EE4J_8/api/pom.xml) has:
``` xml
<![CDATA[
Comments to: <a href="mailto:jsonp-dev@eclipse.org">jsonp-dev@eclipse.org</a>.<br>
Copyright &#169; 2012&#x2013;{currentYear} Oracle and/or its affiliates. All rights reserved.<br>
Use is subject to <a href="{@docRoot}/doc-files/speclicense.html" target="_top">license terms</a>.]]>
```

* Mailing list link (ok, I get it) - why not a link to the project on github too?
* Oracle and affiliates.
* No Eclipse copyright for work done this year.
* Good link to license terms (without mentioning what kind of license it is in the link text)

The above is what I started to use for PR #304 and PR #305, but that's not a wholly fleshed out `<bottom>` section.

[security-api](https://github.com/eclipse-ee4j/security-api/blob/master/api/pom.xml) has:
``` xml
<![CDATA[Copyright &#169; 2015-2017,
    <a href="http://www.oracle.com">Oracle</a>
    and/or its affiliates. All Rights Reserved.
    Use is subject to
    <a href="{@docRoot}/doc-files/speclicense.html" target="_top">license terms</a>.
]]>
```

* No mailing list
* Copyright year range for Oracle in the past.
* No current year.
* License link exists. (but not the actual speclicense.html, as that's missing from their artifact)

So, taking what I've learned from the various ways other projects have done this, the ideal `<bottom>` setup would be ...

* Copyright to Oracle from _inceptionYear_ to 2017.
* Copyright for Oracle includes mention of "and/or its affiliates".
* Copyright to Eclipse Foundation for year 2019.
* Copyright for Eclipse Foundation includes "and/or its affiliates"??
* Link to Mailing list for users.
* Link to Project website for users (`github.com/eclipse-ee4j/<project>`)
* Link to Spec License. (mentioning in link text that it's the "Eclipse Foundation Spec License")

Seeing as this is a legal text matter, this is probably something that should be declared/formalized by Eclipse Legal team and followed strictly by all Jakarta projects.

**Comment by bshannon** [comment]
Thanks, this caused me to research this issue a bit more and come to a new conclusion on
the copyright statement.  Details in [this thread](https://www.eclipse.org/lists/jakartaee-spec-project-leads/msg00170.html).

It should be "Copyright (c) 2019 Eclipse Foundation."  And the javadoc footer should link to
the spec license, which should be included with the javadocs.

**Comment by joakime** [comment]
@bshannon The precise details are still not defined on that thread.

What is the exact `<bottom>` setup supposed to be.
Don't take short-cuts, or use vague language.

If it is truly just `"Copyright (c) 2019 Eclipse Foundation."` then there's no link, either to the `${project.organization.url}`, or the spec license.
If you want those links then either you should be very specific, or just declare the correct `<bottom>` in the parent pom.

Example of second choice:

In the top level parent pom ...

``` xml
    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.5</version> <!-- this would need to be a new version -->
    </parent>
```

https://github.com/eclipse-ee4j/ee4j/blob/master/parent/pom.xml

Could contain a maven-javadoc-plugin declaration with it's own `<bottom>` declaration to have a standard across all projects.

Something along the lines of ...

``` xml
<bottom><![CDATA[Copyright &#169; 2019
    <a href="https://eclipse.org/">Eclipse Foundation</a>
    Use is subject to <a href="{@docRoot}/doc-files/EFSL.html" target="_top">license terms</a>.
]]></bottom>
```

or with `{currentYear}` instead of hardcoded year

``` xml
<bottom><![CDATA[Copyright &#169; ${currentYear}
    <a href="https://eclipse.org/">Eclipse Foundation</a>
    Use is subject to <a href="{@docRoot}/doc-files/EFSL.html" target="_top">license terms</a>.
]]></bottom>
```

or more future proof version with inception year ...

``` xml
<bottom><![CDATA[Copyright &#169; ${project.inceptionYear}&#x2013;${currentYear}
    <a href="https://eclipse.org/">Eclipse Foundation</a>
    Use is subject to <a href="{@docRoot}/doc-files/EFSL.html" target="_top">license terms</a>.
]]></bottom>
```


Then just tell all projects to ...

* Use new project parent
* Don't declare their own maven-javadoc-plugin `<bottom>` section.
* Name their spec license `EFSL.html`

**Comment by bshannon** [comment]
@joakime I'm sorry this is so disorganized.  We're debugging this agile process on the fly.

Your update looks fine for now.  You're right that it would probably be better to configure this
in a parent pom to relieve projects of this burden and to get more consistency.  We would
need to create a spec-specific parent pom, since this configuration doesn't apply to all EE4J
implementation projects.

The original "template" for this called the license file "speclicense.html", but we're not going
to complain if you call it "EFSL.html".  We can choose one and push for consistency in the future.

Also, once we're past 2019, we'll need to list two years in the copyright line.  The Eclipse standard
is to separate the years with a comma (and space), rather than a dash, so we'll need to deal
with that too.

**Comment by joakime** [comment]
After my conversation with @dblevins on issue #295 I'm more aligned to what's expected.

@bshannon I'm closing this issue, as your mailing list thread pretty much invalidates the need for a `<organization>` override now.
