### ISSUE TITLE
Specification Team Review of Specification 1.1(.2)

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/websocket-api#309]
Per checklist at https://github.com/jakartaee/specifications/pull/79#issuecomment-528585080

 - [x] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [x] The specification project team should approve the compatibility request and send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] The specification project team should merge any final release branch as appropriate for the branch management for the project.

---

The WebSocket API specification team needs to follow the above checklist.
The first and last bullet can be done by one person, but the second checklist item needs the team to approve.

**Comment by joakime** [comment]
The specification website page can be found at ...

https://jakarta.ee/specifications/websocket/

The specific page for 1.1 (aka 1.1.2) is at ...

https://jakarta.ee/specifications/websocket/1.1/

**Comment by joakime** [comment]
Results of linkcheck are a success ...

``` shell
$ linkchecker -r 1 https://jakarta.ee/specifications/websocket/1.1/
INFO 2019-09-30 16:29:49,456 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2019-09-30 16:29:49-005
 2 threads active,     0 links queued,   82 links in   3 URLs checked, runtime 1 seconds

Statistics:
Downloaded: 22.83KB.
Content types: 0 image, 9 text, 0 video, 0 audio, 2 application, 0 mail and 73 other.
URL lengths: min=19, max=103, avg=42.

That's it. 84 links in 7 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2019-09-30 16:29:50-005 (1 seconds)
```

**Comment by joakime** [comment]
The compatibility request can be found at Issue https://github.com/eclipse-ee4j/websocket-api/issues/308

@markt-asf can I get a +1 for approval on the compatibility request?

**Comment by markt-asf** [comment]
+1

**Comment by joakime** [comment]
+1 from me

**Comment by bshannon** [comment]
The certification request is already approved.
It's been 10 days with no objections, it's time to send email to tck@eclipse.org.

**Comment by joakime** [comment]
@bshannon email to tck@eclipse.org was sent `Date: Wed, 2 Oct 2019 14:50:05 -0500` (according to gmail)

**Comment by bshannon** [comment]
Thanks, but since you didn't notify us we didn't know that we could update the checklist
to mark this complete.  I'm going to assume that you've also merged any release branch
that was created as part of the release process, and that the released content is now included
in the master branch.  I'm closing this issue.
