### ISSUE TITLE
Remove the automatic module names

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/websocket-api#357]
The automatic module name does not comply with the JPMS module naming conventions as it has "api" at the end.
Since this was not present in Jakarta EE 8 yet either, and Websocket has an additional complication by "client" and "server" APIs the recommendation by the Spec Committee is to remove it from the POM and revisit the module name (automatic or fully qualified module-info) after Jakarta EE 9.

**Comment by joakime** [comment]
Where are these recommendations by the Spec Committee?
Got a link?

**Comment by keilw** [comment]
We gather the analysis here: https://docs.google.com/spreadsheets/d/1g8jYG0JixO3wzZkpeyU1LMIQRhbnZ76kGtdMFE8mieE/edit#gid=0 with Websocket the only one unresolved.
This is the Google Doc with the analysis of options: https://docs.google.com/document/d/1LAAHKPJyREky9fEKv0xFd9IRDgXB58It53ryfyrNPtg/edit
Option F is noted as having a clear preference by the Spec Committee and all other specs have followed it.

**Comment by keilw** [comment]
OSGi bundles "jakarta.websocket" and "jakarta.websocket.client" already existed in Jakarta EE 8 although there they also matched the old package name, so I recommend, we keep the automatic-module names but without the "api" so they are also aligned with the OSGi module definitions that existed before.

**Comment by markt-asf** [comment]
Resolved via #358
