### ISSUE TITLE
Compatibility Certification Request for Eclipse Tyrus 2.0.0-RC1

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/websocket-api#361]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  Eclipse Tyrus 2.0.0-RC1, see TCK Result Summary for the download links
- [x] Specification Name, Version and download URL\
   [Jakarta WebSocket 2.0](https://jakarta.ee/specifications/websocket/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Websocket TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-websocket-tck-2.0.0.zip), SHA-256: 3afbe37c5de2b0bc487b06bda9e82900863a797dcd21a853f63fc46b5592fc9a
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/tyrus/tck/eclipse-tyrus-2.0.0-RC1)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by joakime** [comment]
What needs to happen with this issue?
Someone here says "approved!" and closes the issue?

**Comment by arjantijms** [comment]
Indeed, something like "as project lead or as committer I assert this is complete and can be closed".

**Comment by m0mus** [comment]
... or it's approved by lazy consensus after 21 days

**Comment by arjantijms** [comment]
Closing by lazy consensus then ;)
