### ISSUE TITLE
Ballot for WebSocket 2.0 is approved, please perform the actions listed here

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/websocket-api#363]
Congratulations, the ballot for WebSocket 2.0 has completed and has been approved. Please perform the following actions:
 - [x] promote api staging release, promote the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by markt-asf** [comment]
This was all completed some time ago
