### ISSUE TITLE
Jakarta Websocket webpage contains outdated information for latest download

### ISSUE THREAD

**Issue by apupier** [eclipse-ee4j/websocket-api#364]
https://eclipse-ee4j.github.io/websocket-api/#Download_Jakarta_WebSocket_Release is pointing to Jakarta 1.1.1 as latest release although 2.0.0 has been released https://github.com/eclipse-ee4j/websocket-api/releases/tag/2.0.0-RELEASE and is available on Maven Central

**Comment by markt-asf** [comment]
I've made a first pass at fixing this. The website is still rather thin but the version and links should be updated now.
