### ISSUE TITLE
Not able to get ping and pong message from server to go lang websocket client

### ISSUE THREAD

**Issue by vitpravin** [eclipse-ee4j/websocket-api#366]
Go lang client - https://github.com/gorilla/websocket
From server-side we are sending the ping and pong message but the go lang client is not able to receive 

Tested with different websocket client and server
Below are observations 

Java server and Node Js client = Ping woking
Java server and Go, lang client, = **Ping not working**
server and  Node Js client = Ping Working
server and Go lang client  = Ping working

The only issue we are facing is for the **java server and go lang client**
Java server working with other client and go lang client working with other servers for a ping message

could you please help with this
That would be very helpful

Thanks

**Comment by markt-asf** [comment]
You need to raise this with the respective WebSocket implementations you are using.

**Comment by vitpravin** [comment]
I am using this lib only for java implementations

**Comment by markt-asf** [comment]
Not possible. This library only defines the API. You need to raise an issue with the implementation of this API that you are using.

**Comment by vitpravin** [comment]
Thanks, @markt-asf I have raised the new issue and added the implementation details
