### ISSUE TITLE
Session idle timeout doesn't define behaviour for 0 or negative values

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/websocket-api#382]
A need for this clarification was identified in the discussions around #356 / #377. When those were closed as WONTFIX, this issue was created for this specific clarification.

The clarification is that a zero or negative value disables the timeout.

**Comment by joakime** [comment]
> The clarification is that a zero or negative value disables the timeout.

That works for me.

Thought that's what was in the spec / apidoc already?
Am I mistaken?
