### ISSUE TITLE
Remove GNU license

### ISSUE THREAD

**Issue by arpitjindal97** [eclipse-ee4j/websocket-api#386]
Hello team,

I want to use this library in one of the projects but I'm not able to because of the restrictions imposed by GNU license.

We do not have any problem with EPL.

**Comment by markt-asf** [comment]
Then use the code under the EPLv2. There is no requirement to use the secondary license.

**Comment by arpitjindal97** [comment]
We scan the dependencies using Blackduck. It checks both licenses and gives error on GPL. Would you mind only keeping EPL?

**Comment by markt-asf** [comment]
Sorry, the licensing is not going to change. I'd raise a support issue with Blackduck as the tool is reporting a false positive.

**Comment by joakime** [comment]
We (the committers of this project) are not free to make a licensing change here.  

Contact the Eclipse Foundation and it's representatives on the Eclipse Jakarta EE top level if you have a request to change/alter licenses.

**Comment by jansupol** [comment]
The GPL is known to be a non-permissive license, therefore the classpath exception is added to the license, it is a GPL+CPE license. The project is dual-licensed, though, either of EPL or GPL+CPE can be chosen.
